shop/fresh_shop/cart/urls.py
#coding=utf-8
from django.conf.urls import url

from cart import views

urlpatterns = [
    url(r'^add_cart/',views.add_cart,name='add_cart'),
    # 购物车
    url(r'^cart/',views.cart,name='cart'),
    # 结算
    url(r'^place_order',views.place_order,name='place_order'),
    # 刷新价格
    url(r'^f_price/',views.f_price,name='f_price'),
    # 购物车数据
    url(r'cart_count/',views.cart_count,name='cart_count'),
    # 修改购物车中商品的个数
    url(r'^change_goods_num/',views.change_goods_num,name='change_goods_num'),


]

shop/fresh_shop/fresh_shop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('user.urls',namespace='user')),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/',include('order.urls',namespace='order')),


]
urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

shop/fresh_shop/cart/models.py
#coding=utf-8
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

shop/fresh_shop/cart/views.py
#coding=utf-8
from django.http import JsonResponse
from django.shortcuts import render

from cart.models import ShoppingCart
from goods.models import Goods
from user.models import UserAddress


def add_cart(request):
    if request.method == 'POST':
        # 加入购物车,需判断用户是否登录
        # 如果登录,加入到购物车中的数据,其实就是加入数据库中购物车表中(设计不好的办法)

        # 如果登录,加入数据库中的数据,存储在session中(设计相对较好)
        # 如果没有登录,则加入到购物车的数据,加入到session中
        # session中存储数据:商品id,商品数量,商品的选择状态
        # 如果登录,则把session中数据同步到数据库中(中间件同步数据)

        # 1.获取商品id和商品数量
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        # 2.组装到session中的数据格式
        goods_list = [goods_id,goods_num,1]

        if request.session.get('goods'):
            # 说明session中存储了加入购物车的商品信息
            # 判断当前加入到购物车中的数据,是否已经存在于session中
            # 如果存在,则修改session中该商品的数量
            # 如果不存在,则新增
            flag = 0
            session_goods = request.session['goods']
            for goods in session_goods:
                # 判断如果加入到购物车中数据,已经存在于session中,则修改
                if goods[0] == goods_id:
                    goods[1] = int(goods[1]) + int(goods_num)
                    flag = 1
            if not flag:
                # 如果不存在,则添加
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            goods_count = len(session_goods)
        else:
            data = []
            data.append(goods_list)
            request.session['goods'] = data
            goods_count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功','goods_count':goods_count})

def cart(request):
    if request.method == 'GET':
        # 如果没有登录,则从session中取商品的信息
        # 如果登录,还是从session中取数据(保证数据库中的商品和session中商品一致)
        session_goods = request.session.get('goods')
        if session_goods:
            goods_all = []
            for goods in session_goods:

                cart_goods = Goods.objects.filter(pk=goods[0]).first()
                goods_number = goods[1]
                total_price = goods[1]*cart_goods.shop_price
                goods_all.append([cart_goods,goods_number,total_price])
            # 获取商品对象
            # 前台需要商品信息,商品的个数,商品的总价
            # 后台返回结构 [[goods object,number,total_price],...]

        else:
            goods_all = ''
        return render(request,'cart.html',{'goods_all':goods_all})


def place_order(request):
    if request.method == 'GET':
        user_id = request.session.get('user_id')
        carts = ShoppingCart.objects.filter(user_id=user_id,is_select=1).all()

        for cart in carts:
            # 给每一个购物车商品对象添加一个total_price属性,用于存储总价
            cart.total_price = int(cart.nums) * int(cart.goods.shop_price)

        # 获取订单地址
        addresses = UserAddress.objects.filter(user_id=user_id)
        return render(request,'place_order.html',{'carts':carts,'addresses':addresses})

def f_price(request):
    """
    返回购物车或session中商品的价格和总价
    {key:[[id1,price1],[id2,price2]],key2:total_price}
    :param request:
    :return:
    """
    if request.method == 'GET':
        user_id = request.session.get('user_id')
        if user_id:
            # 获取当前登录系统的用户的购物车的数据
            carts = ShoppingCart.objects.filter(user_id=user_id)
            cart_data = {}
            cart_data['goods_price'] = [(cart.goods_id,
                                         cart.nums * cart.goods.shop_price)
                                        for cart in carts]
            all_price = 0
            # 总的价格
            for cart in carts:
                if cart.is_select:
                    all_price += cart.nums * cart.goods.shop_price
            cart_data['all_price'] = all_price
        else:
            # 拿到session中所有的商品信息,[id,num,is_select]
            session_goods = request.session.get('goods')
            # 返回数据结构,{’goods_price'：[[id1, price1],[id2, price2]...]}
            cart_data = {}
            data_all = {}
            # 计算总价
            all_price = 0
            for goods in session_goods:
                data = []
                data.append(goods[0])
                g = Goods.objects.get(pk=goods[0])
                data.append(int(goods[1]) * g.shop_price )
                # 生成的data为:[id1,price1]
                data_all.append(data)
                # 判断如果商品勾选了,才计算总价格
                if goods[2]:
                    all_price += int(goods[1]) * g.shop_price
            cart_data['goods_price'] = data_all
            cart_data['all_price'] = all_price
        return JsonResponse({'code':200,'cart_data':cart_data})


def cart_count(request):
    if request.method == 'GET':
        # 判断购物车中商品的个数
        user_id = request.session.get('user_id')
        # 当前购物车中的商品数量
        if user_id:
            # 如果用户登录。则回去购物车表中的商品个数
            count = ShoppingCart.objects.filter(user_id=user_id).count()
        else:
            # 如果用户没有登录，则回去session中的商品个数
            session_goods = request.session.get('goods')
            count = len(session_goods)
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def change_goods_num(request):
    if request.method == 'POST':
        # 修改购物车中商品的个数
        # 1. 先判断用户登录与否，如果用户没有登录，则修改session中商品的个数
        # 2. 如果用户登录，需要判断当前修改的商品是否存在于session中，如果存在，则修改session。如果不存在则修改购物车的表
        # 获取修改的商品id，商品个数，商品选择状态
        goods_id = request.POST.get('goods_id')
        goods_num = int(request.POST.get('goods_num'))
        is_select = int(request.POST.get('is_select'))

        user_id = request.session.get('user_id')

        # 先判断要修改的商品是否存在于session中，如果存在则修改session中的商品个数和选择状态
        session_goods = request.session.get('goods')
        # goods的结构为: [id1, num, is_select]
        if session_goods:
            for goods in session_goods:
                if goods_id == goods[0]:
                    # 修改session中商品的个数和选择状态
                    goods[1] = goods_num
                    goods[2] = is_select
            request.session['goods'] = session_goods

        # 如果用户登录了，则需要在修改购物车中数据，因为session中的商品有可能并不在购物车表中
        if user_id:
            # 修改购物车中商品个数
            ShoppingCart.objects.filter(user_id=user_id, goods_id=goods_id).update(nums=goods_num,
                                                                                   is_select=is_select)
        return JsonResponse({'code': 200, 'msg': '请求成功'})

shop/fresh_shop/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    {% block js %}

    {% endblock %}

    {% block css %}
    {% endblock %}

</head>
<body>
{% block header_con %}

{% endblock %}

{% block search %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

{% block endjs %}

{% endblock %}
</body>
</html>

shop/fresh_shop/templates/base_main.html
{% extends 'base.html' %}

{% block css %}
    {% load static  %}
    <link rel="stylesheet" type="text/css" href="{% static  'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock %}


{% block js %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        <!-- 获取用户的登录用户名 -->
        $.get('/user/is_login/', function(data){
            if(data.code == '200'){
                $('.login_info em').html(data.username)
                <!--展示当前用户的信息-->
                $('.login_info').show()
                <!--隐藏登录注册按钮-->
                $('.login_btn').remove()
            }
        })

        <!-- 获取购物车中的商品个数 -->
        $.get('/cart/cart_count/', function(data){
            if(data.code == '200'){
                $('#show_count').html(data.count)
                $('.total_count em').html(data.count)
            }
        })
    </script>
{% endblock %}

{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em></em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">注销</a>

				</div>
				<div class="login_btn fl">

					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center_order' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:user_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block search %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>
{% endblock %}



{% block footer %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

{% endblock %}

shop/fresh_shop/templates/cart.html
{% extends 'base_main.html' %}

{% block title %}
天天生鲜-购物车
{% endblock %}


{% block content %}


	<div class="total_count">全部商品<em>2</em>件</div>


	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

{% if goods_all %}
{% for goods in goods_all %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" {% if goods.2 %} checked {% endif %} onchange="change_select({{ goods.0.id }})"></li>
                <input type="hidden" {% if goods.2 %} value="1" {% else %} value="0" {% endif %} id="goods_select_{{ goods.0.id }}">
		<li class="col02"><img src="/media/{{goods.0.goods_front_image}}"></li>
		<li class="col03">{{goods.0.name}}<br><em>{{goods.0.shop_price}}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{goods.0.shop_price}}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" onclick="add_cart_num({{goods.0.id}});" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{goods.1}}" id="goods_num_{{ goods.0.id }}">
				<a href="javascript:;" onclick="sub_cart_num({{ goods.0.id }})" class="minus fl">-</a>
			</div>

		</li>
		<li class="col07" id="goods_{{ goods.0.id }}">{{goods.2}}元</li>
		<li class="col08"><a href="javascript:;" >删除</a></li>
	</ul>

{% endfor %}
{% endif %}
	<!--定义修改购物车中数量,勾选状态等操作-->
	{% csrf_token %}
	<script type="text/javascript">
		<!--刷新商品的价格-->
        $.get('/cart/f_price/', function(data){
            if(data.code == '200'){
                for(var i=0; i<data.cart_data.goods_price.length;i++){
                    price = data.cart_data.goods_price[i][1] + '元'
                    $('#goods_' + data.cart_data.goods_price[i][0]).html(price)
                }
                $('#total_price em').html(data.cart_data.all_price + '元')
            }
        })

        <!--增加商品的个数-->
        function add_cart_num(goods_id){
            <!--获取商品的个数-->
            var goods_num = $('#goods_num_' + goods_id).val()
            <!--TODO:暂且不判断添加商品是否超过库存-->
            $('#goods_num_' + goods_id).val(parseInt(goods_num) + 1)
            change_cart_num(goods_id)
        }

        <!--减少商品的个数-->
        function sub_cart_num(goods_id){
            <!--获取商品的个数-->
            var goods_num = $('#goods_num_' + goods_id).val()
            <!--判断减少商品的数量不能小于1-->
            num = parseInt(goods_num) - 1
            if(num > 0){
                $('#goods_num_' + goods_id).val(num)
                change_cart_num(goods_id)
            }
        }

        <!--修改商品的选择状态-->
        function change_select(goods_id){
            goods_select = $('#goods_select_' + goods_id).val()
            if(goods_select == '1'){
                $('#goods_select_' + goods_id).val('0')
            }else{
                $('#goods_select_' + goods_id).val('1')
            }
            change_cart_num(goods_id)
        }

        <!--修改商品的个数,选择状态-->
        function change_cart_num(goods_id){
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            <!--获取商品的个数-->
            var goods_num = $('#goods_num_' + goods_id).val()
            <!--获取商品的选择状态-->
            var is_select = $('#goods_select_' + goods_id).val()
            $.ajax({
                url:'/cart/change_goods_num/',
                data:{'goods_id': goods_id, 'goods_num': goods_num, 'is_select': is_select},
                type:'POST',
                dataType:'json',
                headers:{'X-CSRFToken': csrf},
                success:function(data){
                    console.log(data)
                },
                error:function(data){
                    alert('请求失败')
                }
            })
        }
	</script>


	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03" id="total_price" >合计(不含运费)：<span>¥</span><em>0</em></li>
		<li class="col04"><a href="{% url 'cart:place_order' %}">去结算</a></li>
	</ul>


{% endblock %}
	

shop/fresh_shop/templates/detail.html
{% extends 'base_main.html' %}

{% block title %}
天天生鲜-商品详情
{% endblock %}

{% block js %}
	{{ block.super }}
{% endblock %}


{% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/media/{{ goods.goods_front_image }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.name }}</h3>
			<p>{{ goods.goods_brief }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.shop_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" onclick="add_number({{ goods.shop_price }});" class="add fr">+</a>
					<a href="javascript:;" onclick="sub_number({{ goods.shop_price }});" class="minus fr">-</a>
				</div>
				<script type="text/javascript">
					function add_number(price){
						<!--修改商品个数和商品的总价-->
						var num = $('.num_show').val();
						var new_num = parseInt(num) + 1;
						var total_price = price * new_num;
						<!--修改总价-->
						$('.total em').html(total_price +'元');
						<!--修改商品个数-->
						$('.num_show').val(new_num);
					}
					function sub_number(price){
						<!--修改商品个数和商品的总价-->
						var num = $('.num_show').val();
						var new_num = parseInt(num) - 1;
						var total_price = price * new_num;
						if (new_num > 0){
							<!--修改总价-->
							$('.total em').html(total_price +'元');
							<!--修改商品个数-->
							$('.num_show').val(new_num);

						}

					}

				</script>
			</div>
			<div class="total">总价：<em>{{ goods.shop_price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" onclick="add_cart({{goods.id}});" id="add_cart">加入购物车</a>
				{% csrf_token %}
				<script type="text/javascript">
					function add_cart(goods_id){
						var goods_num = $('.num_show').val()
						var csrf = $('input[name="csrfmiddlewaretoken"]').val()
						$.ajax({
							url:'/cart/add_cart/',
							type:'POST',
							dataType:'json',
							headers:{'X-CSRFToken':csrf},
							data:{'goods_id':goods_id,'goods_num':goods_num},
							success:function(data){
								if (data.code == '200'){
									$('#show_count').html(data.goods_count)
								}
							},
							error:function(data){
								alert('添加商品失败')
							}

						})
					}
				</script>
			</div>


		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_desc | safe }}</dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}

{% block endjs%}
	<div class="add_jump"></div>
	{% load static %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.2.js' %}"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		})
	</script>
{% endblock %}

shop/fresh_shop/templates/index.html
{% extends 'base_main.html' %}
{% block title %}
天天生鲜-首页
{% endblock %}





{% block js %}
	{% load static %}
	{{ block.super }}
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'images/slide.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide02.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide03.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'images/slide04.jpg' %}" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}"></a>
		</div>
	</div>

	{% for key,value in goods_dict.items %}

		<div class="list_model">
			<div class="list_title clearfix">
				<h3 class="fl" id="model01">{{ key }}</h3>
				<!--<div class="subtitle fl">-->
					<!--<span>|</span>-->
					<!--<a href="#">鲜芒</a>-->
					<!--<a href="#">加州提子</a>-->
					<!--<a href="#">亚马逊牛油果</a>-->
				<!--</div>-->
				<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
			</div>

			<div class="goods_con clearfix">
				<div class="goods_banner fl"><img src="/media/{{value.0.category.category_front_image }}"></div>
				<ul class="goods_list fl">
					{% for goods in value %}
						<li>
							<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
							<a href="{% url 'goods:detail' goods.id %}"><img src="/media/{{ goods.goods_front_image }}"></a>
							<div class="prize">¥ {{ goods.shop_price }}</div>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	{% endfor %}

{% endblock %}

{% block endjs %}

	<script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>

{% endblock %}

shop/fresh_shop/templates/user_center_info.html
{% extends  'base_main.html' %}

{% block ticle %}
    天天生鲜-商品详情
{% endblock %}

{% block content %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_order' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'order:user_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'order:user_order_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
					<ul class="user_info_list">
						<li><span>用户名：</span>{{ user.username }}</li>
						<li><span>联系方式：</span>
							{% if user.mobile %}
								{{ user.mobile }}
							{% else %}
								暂无
							{% endif %}
						</li>
					</ul>
				</div>
				<h3 class="common_title2">最近浏览(TODO:该功能保留，后期继续开发)</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<!--<a href="detail.html"><img src="images/goods/goods003.jpg"></a>-->
					<!--<h4><a href="detail.html">大兴大棚草莓</a></h4>-->
					<!--<div class="operate">-->
						<!--<span class="prize">￥16.80</span>-->
						<!--<span class="unit">16.80/500g</span>-->
						<!--<a href="#" class="add_goods" title="加入购物车"></a>-->
					<!--</div>-->
				</li>
			</ul>
		</div>
		</div>
	</div>

{% endblock %}